[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
addopts = -v -s --tb=short
markers =
    smoke: быстрые smoke-тесты
    api: backend / HTTP тесты
    ui: Selenium UI тесты
    selenium: UI-тесты на Selenium WebDriver
    playwright: UI-тесты на Playwright
    network: проверка сетевых запросов браузера
