apiVersion: 1

datasources:
  - name: InfluxDB-BID
    uid: InfluxDB-BID
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: bid
      defaultBucket: bid_monitor
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
